name: Blob storage website CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        working-directory: tests
  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
            az storage blob upload-batch --account-name grants4all --destination '$web' --source src
    #- name: Purge CDN endpoint
    #  uses: azure/CLI@v1
    #  with:
    #    azcliversion: 2.0.72
    #    inlineScript: |
    #       az cdn endpoint purge --content-paths  "/*" --profile-name "CDN_PROFILE_NAME" --name "CDN_ENDPOINT" --resource-group "RESOURCE_GROUP"

  # Azure logout
    - name: logout
      run: |
            az logout
